// ([1-9])\.([1-9])\s(.*) --> '$1_$2': "$3",
export const descriptions = {
    architectural_graphics:
    {
        '1_1': "Szentendre - Művésztelep pályázat - utcakép",
        '1_2': "Mesteriskola pályázat - homlokzat ",
        '1_3': "Mesteriskola pályázat - homlokzat",
        '1_4': "Mesteriskola pályázat - vázlatok",
        '2_1': "MKE - művésztanár szak - város koncepciók",
        '2_2': "MKE - művésztanár szak - város koncepciók",
        '2_3': "MKE - művésztanár szak - város koncepciók",
        '2_4': "MKE - művésztanár szak - város koncepciók",
        '3_1': "Reinzink stand kézi látványterv ",
        '3_2': "Ilkatin étterem kézi látványterv - Tuba Reklámstúdió",
        '3_3': "Ilkatin étterem kézi látványterv - Tuba Reklámstúdió",
        '3_4': "Közgáz büfé kézi látványterv",
        '4_1': "Moholy Nagy Művészeti Egyetem - építész tervek",
        '4_2': "Moholy Nagy Művészeti Egyetem - építész tervek",
        '4_3': "Moholy Nagy Művészeti Egyetem - építész tervek",
        '4_4': "Moholy Nagy Művészeti Egyetem - építész tervek"
    },
    students_work: {

        '1_1': "Dér Kata - Tanulmányok",
        '1_2': "Dér Kata - minta terv",
        '1_3': "Dér Kata - minta terv",
        '1_4': "Dér Kata - pult látványtervek tervezett mintával ",
        '2_1': "Dér Kata - Szalézi Aula pultterv",
        '2_2': "Faltis Roberta - katonaperspektíva",
        '2_3': "Németh Anna - Színes alaprajz",
        '2_4': "Németh Anna - Lakás falnézetek",
        '3_1': "Dénes Boglárka - Lakás látványterv",
        '3_2': "Dénes Boglárka - lakás látványterv",
        '3_3': "Dénes Boglárka - Lakás látványterv",
        '3_4': "Dénes Boglárka - Lakás látványterv",
        '4_1': "Németh Anna - moodboard",
        '4_2': "Németh Anna - Egyszerűsítés folyamata",
        '4_3': "Németh Anna - Mintatervezés folyamata",
        '4_4': "Németh Anna - Mintatervezés folyamata",
        '5_1': "Percze Fanni - lakás látványterv",
        '5_2': "Percze Fanni - lakás látványterv",
        '5_3': "Percze Fanni - lakás látványterv",
        '5_4': "Percze Fanni - lakás látványterv",
        '6_1': "Pongrácz Ildi vizsgamunka, Mozi-, és Rendezvényház",
        '6_2': "Pongrácz Ildi vizsgamunka, Mozi-, és Rendezvényház",
        '6_3': "Pongrácz Ildi vizsgamunka, Mozi-, és Rendezvényház",
        '6_4': "Pongrácz Ildi vizsgamunka, Mozi-, és Rendezvényház"
    },
    graphics:
    {
        '1_1': "Gazda utca télen",
        '1_2': "Cseresznyefa",
        '1_3': "Hidegkút télen",
        '1_4': "Solymár felé",
        '2_1': "Kisfiú ünnepi ültözetben",
        '2_2': "Cséplés közben",
        '2_3': "Kislány a víztározónál",
        '2_4': "Kislányok",
        '3_1': "Kroki",
        '3_2': "Fekvő akt",
        '3_3': "Kroki",
        '3_4': "Fekvő akt",
        '4_1': "Portré",
        '4_2': "Portré",
        '4_3': "Portré",
        '4_4': "Portré",
        '5_1': "Tanulmányrajz",
        '5_2': "Portré",
        '5_3': "Portré",
        '5_4': "Hölgy kalapban"
    },

    interieur_architecture:
    {
        '1_1': "Angyal Hotel - Batimage Architect",
        '1_2': "Angyal Hotel - Batimage Architect",
        '1_3': "GY.M. lakás belsőépítészeti tervezés",
        '1_4': "GY.M. lakás belsőépítészeti tervezés",
        '2_1': "MTA Székház belsőépítészet - Teampannon, Sandroza",
        '2_2': "MTA Székház belsőépítészet - Teampannon, Sandroza",
        '2_3': "Művészetek Palotája - Zoboki, Technoart",
        '2_4': "Művészetek Palotája - Zoboki, Technoart",
        '3_1': "Szekszárd, Polgárimesteri Hivatal ",
        '3_2': "Szekszárd, Polgárimesteri Hivatal ",
        '3_3': "Szekszárd, Polgárimesteri Hivatal ",
        '3_4': "Szekszárd, Polgárimesteri Hivatal ",
        '4_1': "Bük, Szapáry Kastély",
        '4_2': "Bük, Szapáry Kastély",
        '4_3': "Bük, Szapáry Kastély",
        '4_4': "Bük, Szapáry Kastély",
        '5_1': "Space Light System - látványterv",
        '5_2': "Space Light System - látványterv",
        '5_3': "Space Light System - látványterv",
        '5_4': "Space Light System - Design week",
        '6_1': "Reinzink stand - Tuba Reklámstúdió",
        '6_2': "Reinzink stand - Tuba Reklámstúdió",
        '6_3': "Reinzink stand - Tuba Reklámstúdió",
        '6_4': "Reinzink stand - Tuba Reklámstúdió"
    }
}

export const technique = {
    graphics:
    {
        '1_1': "toll, grafit",
        '1_2': "toll, grafit",
        '1_3': "toll, grafit",
        '1_4': "toll, grafit",
        '2_1': "toll, grafit",
        '2_2': "toll, grafit",
        '2_3': "toll, grafit",
        '2_4': "toll, grafit",
        '3_1': "toll, grafit",
        '3_2': "ceruza",
        '3_3': "ceruza",
        '3_4': "ceruza",
        '4_1': "kréta",
        '4_2': "kréta",
        '4_3': "kréta",
        '4_4': "kréta",
        '5_1': "szénceuza",
        '5_2': "szénceuza",
        '5_3': "szénceuza",
        '5_4': "szénceuza"
    },
}
